services:
  authAppFastAPI:
    image: thibaultsan/auth-app:latest
    restart: on-failure
    environment:
      - DB_URL=host=db port=5432 user=postgres dbname=Auth_App password=postgres sslmode=disable
    ports:
      - "3500:3200"
    links:
      - db
  db:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-app
volumes:
  db-storage: